### ISSUE TITLE
Redwood launcher gets crashed very often

### ISSUE THREAD

**Issue by GopalSingh292** [Talentica/Wheat#1]
This is the error message
"Error: Could not find or load main class redwood.launcher.Launcher"

Once in 5 times it works fine on an average

**Comment by dinkar19121991** [comment]
@GopalSingh292 can you please provide detailed log(redwoodHQ agent and appium) and scenario you were trying to achieve

**Comment by sapins** [comment]
@GopalSingh292 
Please restart your redwoodHQ agent and try to execute test cases.
